version: "3.9"

services:
  app:
    container_name: next-app-sandbox
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/app
    environment:
      - WATCHPACK_POLLING=true
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
